# Generated by Django 2.1 on 2018-08-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_user_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gaming',
            field=models.BooleanField(default=False),
        ),
    ]
