# Generated by Django 2.1 on 2018-08-11 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_user_gaming'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_timestamp', models.DateField(auto_now=True)),
                ('fromuser', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fk_i_f_id', to='game.User')),
                ('touser', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fk_i_t_id', to='game.User')),
            ],
        ),
    ]
