# Generated by Django 2.1 on 2018-08-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='board',
            field=models.CharField(default='222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222', max_length=255),
        ),
    ]
